### PR TITLE
Old-WIP: Implementation of saucectl-run-action

### PR DESCRIPTION
**Pull request by FriggaHel**
Base implementation of saucectl run action.

### CODE REVIEW

**Comment by christian-bromann** [comment]
@FriggaHel I don't think we need to check in the `node_modules`, no?

**Comment by FriggaHel** [comment]
> @FriggaHel I don't think we need to check in the `node_modules`, no?

@christian-bromann  Action is just fetch and executed, there is no step where dependencies are installed. This `node_modules` contains only the `productions` one. I agree this is not the cleanest approach at all.

Ref: https://docs.github.com/en/actions/creating-actions/creating-a-javascript-action#commit-tag-and-push-your-action-to-github

**Comment by christian-bromann** [comment]
What about the suggestions of using `vercal/ncc` or similar what we do in [`saucelabs/sauce-connect-docker`](https://github.com/saucelabs/sauce-connect-action) use the TypeScript compiler to create a single distribution file?

**Comment by FriggaHel** [comment]
> What about the suggestions of using `vercal/ncc` or similar what we do in [`saucelabs/sauce-connect-docker`](https://github.com/saucelabs/sauce-connect-action) use the TypeScript compiler to create a single distribution file?

I will take a look to that option @christian-bromann ! Thanks for the tip !

**Pull request closed without merging**
